Merging upstream version 0.7.5.

diff --git a/src/lxc/lxc-ls.in b/src/lxc/lxc-ls.in
--- a/src/lxc/lxc-ls.in
+++ b/src/lxc/lxc-ls.in
@@ -10,15 +10,19 @@ function get_cgroup()
 {
 	local mount_string
 	mount_string=$(mount -t cgroup |grep -E -e '^lxc ')
-	if test -z "$mount_string"; then
-		mount_string=$(mount |grep -m1 'type cgroup')
-	fi
 	if test -n "$mount_string"; then
 		mount_point=$(echo $mount_string |cut -d' ' -f3)
+		return
 	fi
+	mount_string=`grep -m1 -E '^[^ \t]+[ \t]+[^ \t]+[ \t]+cgroup' /proc/self/mounts`;
+	if test -z "$mount_string"; then
+		echo "failed to find mounted cgroup"
+		exit 1
+	fi
+	mount_point=`echo "$mount_string" |cut -d' ' -f2`;
 }
 
-ls $* $lxcpath
+ls "$@" $lxcpath
 
 active=$(netstat -xa | grep $lxcpath | \
 	sed -e 's#.*'"$lxcpath/"'\(.*\)/command#\1#');
@@ -26,6 +30,6 @@ active=$(netstat -xa | grep $lxcpath | \
 if test -n "$active"; then
 	get_cgroup
 	if test -n "$mount_point"; then
-		cd $mount_point; ls $* -d $active
+		cd $mount_point; ls "$@" -d $active
 	fi
 fi
