Merging upstream version 0.7.4.2.

diff --git a/templates/lxc-lucid.in b/templates/lxc-lucid.in
--- a/templates/lxc-lucid.in
+++ b/templates/lxc-lucid.in
@@ -1,37 +1,34 @@
 #!/bin/bash
 
 #
-# template script for generating fedora container for LXC
+# template script for generating ubuntu/lucid container for LXC
+#
+# This script is based on lxc-debian (Daniel Lezcano <daniel.lezcano@free.fr>)
 #
 
+# Copyright © 2010 Wilhelm Meier
+# Author: Wilhelm Meier <wilhelm.meier@fh-kl.de>
 #
-# lxc: linux Container library
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License version 2, as
+# published by the Free Software Foundation.
 
-# Authors:
-# Daniel Lezcano <daniel.lezcano@free.fr>
-
-# This library is free software; you can redistribute it and/or
-# modify it under the terms of the GNU Lesser General Public
-# License as published by the Free Software Foundation; either
-# version 2.1 of the License, or (at your option) any later version.
-
-# This library is distributed in the hope that it will be useful,
+# This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
- # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
-# Lesser General Public License for more details.
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
 
-# You should have received a copy of the GNU Lesser General Public
-# License along with this library; if not, write to the Free Software
-# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
+# You should have received a copy of the GNU General Public License along
+# with this program; if not, write to the Free Software Foundation, Inc.,
+# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
+#
 
-DISTRO=fedora-10
-
-configure_fedora()
+configure_ubuntu()
 {
     rootfs=$1
     hostname=$2
 
-    # disable selinux in fedora
+    # disable selinux in ubuntu
     mkdir -p $rootfs/selinux
     echo 0 > $rootfs/selinux/enforce
 
@@ -67,6 +64,37 @@ script
         /sbin/initctl emit stopped JOB=udevtrigger --no-wait
         /sbin/initctl emit started JOB=udev --no-wait
 end script
+EOF
+
+    # fix buggus runlevel with sshd
+    cat <<EOF > $rootfs/etc/init/ssh.conf
+# ssh - OpenBSD Secure Shell server
+#
+# The OpenSSH server provides secure shell access to the system.
+
+description	"OpenSSH server"
+
+start on filesystem
+stop on runlevel [!2345]
+
+expect fork
+respawn
+respawn limit 10 5
+umask 022
+# replaces SSHD_OOM_ADJUST in /etc/default/ssh
+oom never
+
+pre-start script
+    test -x /usr/sbin/sshd || { stop; exit 0; }
+    test -e /etc/ssh/sshd_not_to_be_run && { stop; exit 0; }
+    test -c /dev/null || { stop; exit 0; }
+
+    mkdir -p -m0755 /var/run/sshd
+end script
+
+# if you used to set SSHD_OPTS in /etc/default/ssh, you can change the
+# 'exec' line here instead
+exec /usr/sbin/sshd
 EOF
 
     cat <<EOF > $rootfs/etc/init/console.conf
@@ -114,21 +142,23 @@ EOF
     return 0
 }
 
-download_fedora()
+download_ubuntu()
 {
+    packages=dialog,apt,apt-utils,resolvconf,iproute,inetutils-ping,vim,dhcp3-client,ssh,lsb-release,gnupg
+
     cache=$1
     arch=$2
 
-    # check the mini fedora was not already downloaded
+    # check the mini ubuntu was not already downloaded
     mkdir -p "$cache/partial-$arch"
     if [ $? -ne 0 ]; then
 	echo "Failed to create '$cache/partial-$arch' directory"
 	return 1
     fi
 
-    # download a mini fedora into a cache
-    echo "Downloading fedora minimal ..."
-    febootstrap $DISTRO $cache/partial-$arch
+    # download a mini ubuntu into a cache
+    echo "Downloading ubuntu lucid minimal ..."
+    debootstrap --verbose --variant=minbase --components=main,universe --arch=$arch --include=$packages lucid $cache/partial-$arch
     if [ $? -ne 0 ]; then
 	echo "Failed to download the rootfs, aborting."
 	return 1
@@ -140,21 +170,21 @@ download_fedora()
     return 0
 }
 
-copy_fedora()
+copy_ubuntu()
 {
     cache=$1
     arch=$2
     rootfs=$3
 
-    # make a local copy of the minifedora
+    # make a local copy of the miniubuntu
     echo -n "Copying rootfs to $rootfs ..."
     cp -a $cache/rootfs-$arch $rootfs || return 1
     return 0
 }
 
-install_fedora()
+install_ubuntu()
 {
-    cache="/var/cache/lxc/fedora"
+    cache="/var/cache/lxc/lucid"
     rootfs=$1
     mkdir -p /var/lock/subsys/
     (
@@ -165,18 +195,25 @@ install_fedora()
 	fi
 
 	arch=$(arch)
+	if [ "$arch" == "x86_64" ]; then
+	    arch=amd64
+	fi
+
+	if [ "$arch" == "i686" ]; then
+	    arch=i386
+	fi
 
 	echo "Checking cache download in $cache/rootfs-$arch ... "
 	if [ ! -e "$cache/rootfs-$arch" ]; then
-	    download_fedora $cache $arch
+	    download_ubuntu $cache $arch
 	    if [ $? -ne 0 ]; then
-		echo "Failed to download 'fedora base'"
+		echo "Failed to download 'ubuntu lucid base'"
 		return 1
 	    fi
 	fi
 
 	echo "Copy $cache/rootfs-$arch to $rootfs ... "
-	copy_fedora $cache $arch $rootfs
+	copy_ubuntu $cache $arch $rootfs
 	if [ $? -ne 0 ]; then
 	    echo "Failed to copy rootfs"
 	    return 1
@@ -202,8 +239,6 @@ lxc.tty = 4
 lxc.pts = 1024
 lxc.rootfs = $rootfs
 lxc.mount  = $path/fstab
-
-lxc.console = /dev/console
 
 lxc.cgroup.devices.deny = a
 # /dev/null and zero
@@ -238,7 +273,7 @@ EOF
 
 clean()
 {
-    cache="/var/cache/lxc/fedora"
+    cache="/var/cache/lxc/lucid"
 
     if [ ! -e $cache ]; then
 	exit 0
@@ -291,9 +326,9 @@ if [ ! -z "$clean" -a -z "$path" ]; then
     exit 0
 fi
 
-type febootstrap
+type debootstrap
 if [ $? -ne 0 ]; then
-    echo "'febootstrap' command is missing"
+    echo "'debootstrap' command is missing"
     exit 1
 fi
 
@@ -309,15 +344,15 @@ fi
 
 rootfs=$path/rootfs
 
-install_fedora $rootfs
+install_ubuntu $rootfs
 if [ $? -ne 0 ]; then
-    echo "failed to install fedora"
+    echo "failed to install ubuntu lucid"
     exit 1
 fi
 
-configure_fedora $rootfs $name
+configure_ubuntu $rootfs $name
 if [ $? -ne 0 ]; then
-    echo "failed to configure fedora for a container"
+    echo "failed to configure ubuntu lucid for a container"
     exit 1
 fi
 
